spring:
  rabbitmq:
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_HOST:localhost}
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB}
  datasource:
    url: jdbc:postgresql://${POSTCODE_IO_HOST:localhost}:${POSTCODE_IO_PORT:5432}/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
rabbit-mq-consumer:
  concurrent-consumers: 40
  prefetch-count: 300
